### ISSUE TITLE
RGB shows as GRB

### ISSUE THREAD

**Issue by Franz888** [blaz-r/pi_pico_neopixel#1]
Running the library on my computer in "RGB":
RED = (0,10,0) instead of (10,0,0)

**Comment by Franz888** [comment]
Solved. Did not read the instructions carefully.

**Comment by blaz-r** [comment]
Yeah, you need to specify the order. Usually with these leds it's GRB not even RGB, but the library supports any order. 

Mind that order of color components in function arguments is always (R, G, B). The order setting is just used so the bits representing each color are sent in right order from board to led-strip. This way functions work the same for any configuration.
