### ISSUE TITLE
 RGB WS2812 problem: must init with GRB in stead of RGB

### ISSUE THREAD

**Issue by nbrok** [blaz-r/pi_pico_neopixel#11]
I'm using a RGB ES2812 in an Elektor Pi Pico experimenting kit with 8 leds and while using your library I get wrong colors when using RGB. Using GRB solves this. As example I use rainbow.py.
The init is done as : strip = Neopixel(numpix, 0, 16, "GRB") numpix is 8.

**Comment by blaz-r** [comment]
I think this is expected behavior as most ws2812 strips actually use GRB bit order.
Mind that order of color components in function arguments is always (R, G, B). The order setting "GRB" is just used so the bits representing each color are sent in right order from board to led-strip.

**Comment by nbrok** [comment]
Thanks for your fast response. So GRB tells the right order to sent the bits to the display.... I'm glad that all is working as to be expected. Thanks.

**Comment by blaz-r** [comment]
Glad to help :)
