### ISSUE TITLE
Neopixel not working

### ISSUE THREAD

**Issue by Jimminer** [blaz-r/pi_pico_neopixel#13]
Hello, I have a raspberry pi pico clone that has an integrated neopixel (WS2812) on pin GPIO23.

I tried using this library in order to control it but it doesn't turn on at all.

The first thing I tried was the example "rainbow.py" and that example happens to have the mode as "RGBW".
Now from what I can tell, an WS2812 neopixel supports only RGB so that is my only clue as to what went wrong.

Is it the case that I blew the neopixel because of the RGBW mode or am I doing something wrong with my code?

**Comment by blaz-r** [comment]
Hello,
if you use RGBW on RGB ledstrip, it shouldn't ruin it. What usually happens is that the colors are not correct. If I understand correctly this WS2812 is integrated on the circuit, so I'm not sure if this library will work at all as it uses PIO and I don't know if PIO is connected to that pin in your case.

**Comment by Jimminer** [comment]
Hello and thanks for the reply.

The schematic for the board shows a connection between GPIO23 and the input of the neopixel with a resistor (0.06Ω) which was not present on the board.
That is done intentionally because you can use the GPIO23 pin externally via the pin header.

It is up to the user to choose if they want to use the pin as an internal neopixel connection or as an external I/O.

If you choose to use it for the neopixel, you can just solder the connections for the resistors together. The resistor's name on the board is "RGB" but because of the bad lettering you might see it as "R68".

Also, here is the board's schematic: https://grobotronics.com/images/companies/1/rp2040-yd_schematics.pdf
