### ISSUE TITLE
Clear()

### ISSUE THREAD

**Issue by spaceddoggy** [blaz-r/pi_pico_neopixel#14]
Strip.clear does not seem to be defined and throws up an error in my code on a Pico running under Thonny. All other commands seem fine

**Comment by blaz-r** [comment]
Hello, I don't know why that would be an issue as it should work. Did you use correct instruction. If you named your object `strip` then it should be `strip.clear()`. It would also help if you sent an exact exception message.
Hope this helped :)

**Comment by spaceddoggy** [comment]
Thanks I'll do that


Best Wishes
Colin R
☎️ 07851225971
☎️ 01684 310628

**Comment by spaceddoggy** [comment]
[image: image.png]
Regards
Colin R

**Comment by spaceddoggy** [comment]
Traceback (most recent call last):

File "<stdin>", line 43, in <module>

AttributeError: 'Neopixel' object has no attribute 'clear'

**Comment by spaceddoggy** [comment]
Ive sorted it now. For some reason I had downloaded an older version of  neopixel.py which didnt have the clear function in it.  I  have now got the up todate version which works fine.
Thanks

**Comment by blaz-r** [comment]
Glad to hear its working now ☺️
