### ISSUE TITLE
Pico W Errno 12 ENOMEM

### ISSUE THREAD

**Issue by map7** [blaz-r/pi_pico_neopixel#9]
I'm running a Pico W with firmware 1.19.1 and I'm getting this error when running the rainbow.py example after about 8 or 9 times of running it through Thonny without detaching the PI.

MicroPython v1.19.1 on 2022-10-05; Raspberry Pi Pico W with RP2040
Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "neopixel.py", line 97, in __init__
OSError: [Errno 12] ENOMEM

**Comment by blaz-r** [comment]
I did some googling and found this: https://forums.raspberrypi.com/viewtopic.php?t=338158
Based on the link above it might be due to PIO memory not being properly cleared on rerun.
Might be a Pico W issue, I'll try it on my pico and report back, otherwise the link above specifies a workaround.

**Comment by blaz-r** [comment]
I tested this on my Pico and it works without any errors even after many restarts. So the problem might be in Pico W not clearing PIO memory and possibly solved as shown in link I posted above. Can you try adding ```rp2.PIO(0).remove_program()``` at the beginning of your code, where you replace 0 with your selected PIO id, and report back?

**Comment by SylivanKenobi** [comment]
I had the same issue on my pico w. Your fix worked for me.

**Comment by blaz-r** [comment]
Nice, thanks for feedback :)
